version: '3.8'

services:
  backend_rag_web:
    container_name: backend_rag_web
    build: .
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PYTHONUNBUFFERED=1
    command: gunicorn --bind 0.0.0.0:8000 run:app --log-level=debug